### ISSUE TITLE
blog ppt

### ISSUE THREAD

**Issue by wfb29** [liuzhengyang/lzy#1]
你好，在https://liuzhengyang.github.io/presentation/里面挂的PPT
问题排查方法，这个主题挂的也是netty的，是不是有误？
https://liuzhengyang.github.io/images/liuzhengyang_netty_presentation.pptx

**Comment by liuzhengyang** [comment]
oh, 是的，修改了。

**Comment by wfb29** [comment]
哈，去拜读下！
